name: build

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            preset: linux
          - os: macos-latest
            preset: macos
          - os: windows-latest
            preset: windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Configure
        run: cmake --preset ${{ matrix.preset }}
      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}
      - name: Test
        run: ctest --preset ${{ matrix.preset }}
